# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy application code
COPY my_fisrt_mcp/ .

# Install dependencies
RUN pip install --no-cache-dir \
    httpx>=0.28.1 \
    mcp[cli]>=1.9.2 \
    openai>=1.82.1

# Expose default port for HTTP
ENV PORT=8080

# Default command to run the MCP server
CMD ["python", "main.py"]
